# Generated by Django 4.2.21 on 2026-05-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
