# Generated by Django 4.2.21 on 2026-05-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroomr',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chatroomr',
            name='user2',
        ),
        migrations.AddField(
            model_name='chatroomr',
            name='max_members',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='chatroomr',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroomr',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chatroomr',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomowner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroomr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
