# Generated by Django 4.2.21 on 2026-05-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_joinrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreindRequest',
        ),
    ]
