# Generated by Django 4.2.21 on 2026-04-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
