# Generated by Django 4.2.21 on 2026-05-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_productapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
